LightWeightDjango/C8-DjangoOnTornado/scrum/board/urls.py
from rest_framework.routers import DefaultRouter
from board import views

router = DefaultRouter(trailing_slash=False)
router.register(r'sprints', views.SprintViewSet)
router.register(r'tasks', views.TaskViewSet)
router.register(r'users', views.UserViewSet)

LightWeightDjango/C8-DjangoOnTornado/scrum/scrum/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from rest_framework.authtoken.views import obtain_auth_token
from board.urls import router
from django.views.generic import TemplateView

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^api/token/', obtain_auth_token, name='api-token'),
    url(r'^api/', include(router.urls)),
    url(r'^$', TemplateView.as_view(template_name='board/index.html')),
]

LightWeightDjango/C8-DjangoOnTornado/scrum/board/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
# Create your models here.

class Sprint(models.Model):
    name = models.CharField(max_length=100, blank=True, default='')
    description = models.TextField(blank=True, default='')
    end = models.DateField(unique=True)

    def __str__(self):
        return self.name or _('Sprint ending %s' % self.end)

class Task(models.Model):
    STATUS_TODO = 1
    STATUS_IN_PROGRESS = 2
    STATUS_TESTING = 3
    STATUS_DONE = 4

    STATUS_CHOICES = (
        (STATUS_TODO, _('Not Started')),
        (STATUS_IN_PROGRESS, _('In Progress')),
        (STATUS_TESTING, _('Testing')),
        (STATUS_DONE, _('Done')),
    )

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, default='')
    sprint = models.ForeignKey(Sprint, blank=True, null=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICES, default=STATUS_TODO)
    order = models.SmallIntegerField(default=0)
    assigned = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    started = models.DateField(blank=True, null=True)
    due = models.DateField(blank=True, null=True)
    completed = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name

LightWeightDjango/C8-DjangoOnTornado/scrum/board/forms.py
import django_filters
from django.contrib.auth import get_user_model
from board.models import Task, Sprint

User = get_user_model()

class NullFilter(django_filters.BooleanFilter):

    def filter(self, qs, value):
        if value is not None:
            return qs.filter(**{'%s__isnull' % self.name: value})
        return qs

class TaskFilter(django_filters.FilterSet):
    backlog = NullFilter(name='sprint')

    class Meta:
        model = Task
        fields = ('sprint', 'status', 'assigned', 'backlog',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.filters['assigned'].extra.update(
            {'to_field_name': User.USERNAME_FIELD}
        )

class SprintFilter(django_filters.FilterSet):
    end_min = django_filters.DateFilter(name='end', lookup_expr='gte')
    end_max = django_filters.DateFilter(name='end', lookup_expr='lte')

    class Meta:
        model = Sprint
        fields = ('end_min', 'end_max',)

LightWeightDjango/C8-DjangoOnTornado/scrum/board/views.py
import hashlib
import requests
from django.contrib.auth import get_user_model
# from django.shortcuts import render
from rest_framework.renderers import JSONRenderer
from rest_framework import viewsets, authentication, permissions, filters
from board.models import Sprint, Task
from board.serializers import SprintSerializer, TaskSerializer, UserSerializer
from board.forms import TaskFilter, SprintFilter

from django.conf import settings
from django.core.signing import TimestampSigner

# Create your views here.
User = get_user_model()

class UpdateHookMixin(object):
    """Mixin class to send update information to the websocket server"""

    def _build_hook_url(self, obj):
        if isinstance(obj, User):
            model = 'user'
        else:
            model = obj.__class__.__name__.lower()
        return '{}://{}/{}/{}'.format(
            'https' if settings.WATERCOOLER_SECURE else 'http',
            settings.WATERCOOLER_SERVER, model, obj.pk
        )

    def _build_hook_signature(self, method, url, body):
        signer = TimestampSigner(settings.WATERCOOLER_SECRET)
        value = '{method}:{url}:{body}'.format(
            method=method.lower(),
            url=url,
            body=hashlib.sha256(body or b'').hexdigest()
        )
        return signer.sign(value)

    def _send_hook_request(self, obj, method):
        url = self._build_hook_url(obj)
        if method in ('POST', 'PUT'):
            # Build the body
            serializer = self.get_serializer(obj)
            renderer = JSONRenderer()
            context = {'request': self.request}
            body = renderer.render(serializer.data, renderer_context=context)
        else:
            body = None

        headers = {
            'content-type': 'application/json',
            'X-Signature': self._build_hook_signature(method, url, body)
        }

        try:
            response = requests.request(method, url, timeout=0.5, headers=headers)
            response.raise_for_status()
        except requests.exceptions.ConnectionError:
            # Host could not be resolved or the connection was refused
            pass
        except requests.exceptions.Timeout:
            # Request timed out
            pass
        except requests.exceptions.RequestException:
            # Server responsed with 4xx or 5xx status code
            pass

    def perform_create(self, serializer):
        super().perform_create(serializer)
        self._send_hook_request(serializer.instance, 'POST')

    def perform_update(self, serializer):
        super().perform_update(serializer)
        self._send_hook_request(serializer.instance, 'PUT')

    def perform_destroy(self, instance):
        self._send_hook_request(instance, 'DELETE')
        super().perform_destroy(instance)


class DefaultsMixin(object):
    authentication_classes = (
        authentication.BasicAuthentication,
        authentication.TokenAuthentication,
    )
    permission_classes = (
        permissions.IsAuthenticated,
    )
    paginate_by = 25
    paginate_by_param = 'page_size'
    max_paginate_by = 100
    filter_backends = (
        filters.DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    )

class SprintViewSet(DefaultsMixin, UpdateHookMixin, viewsets.ModelViewSet):
    queryset = Sprint.objects.order_by('end')
    serializer_class = SprintSerializer
    filter_class = SprintFilter
    search_fields = ('name',)
    ordering_fields = ('end', 'name',)

class TaskViewSet(DefaultsMixin, UpdateHookMixin, viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    filter_class = TaskFilter
    search_fields = ('name', 'description',)
    ordering_fields = ('name', 'order', 'started', 'due', 'completed',)

class UserViewSet(DefaultsMixin, UpdateHookMixin, viewsets.ReadOnlyModelViewSet):
    lookup_field = User.USERNAME_FIELD
    lookup_url_kwarg = User.USERNAME_FIELD
    queryset = User.objects.order_by(User.USERNAME_FIELD)
    serializer_class = UserSerializer
    search_fields = (User.USERNAME_FIELD,)

LightWeightDjango/C8-DjangoOnTornado/scrum/board/templates/board/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <title>Scrum Board</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'board/vendor/normalize.css' %}" media="screen" title="no title">
        <link rel="stylesheet" href="{% static 'board/css/board.css' %}" media="screen" title="no title">

        <!-- home script -->
        <script type="text/html" id="home-template">
            <!-- <h1>Welcome to my Scrum Board Project!</h1> -->
            <h2>Your Sprints</h2>
            <button class="add" type="submit">Add Sprint</button>
            <% if (sprints !== null) { %>
                <div class="sprints">
                    <% _.each(sprints.models, function (sprint) { %>
                        <a href="#sprint/<%- sprint.get('id') %>" class="sprint">
                            <%- sprint.get('name') %> <br>
                            <span>DUE BY <%- sprint.get('end') %></span>
                        </a>
                    <% }); %>
                </div>
                <% }else{ %>
                    <h3 class="loading">Loading...</h3>
            <% } %>
        </script>

        <!-- login script -->
        <script type="text/html" id="login-template">
            <form action="" method="post">
                <label for="id_username">Username</label>
                <input id="id_username" type="text" name="username" maxlength="30" required value="">
                <label for="id_password">Password</label>
                <input type="id_password" type="password" name="password" required value="">
                <button type="submit">Login</button>
            </form>
        </script>

        <!-- header script -->
        <script type="text/html" id="header-template">
            <span class="title">Scrum Board Example</span>
            <% if(authenticated) { %>
                <nav>
                    <a href="/" class="button">Your Sprints</a>
                    <a href="#" class="logout button">Logout</a>
                </nav>
            <% } %>
        </script>

        <!-- new sprint script -->
        <script type="text/html" id="new-sprint-template">
            <form action="" method="post">
                <label for="id_name">Sprint Name</label>
                <input id="id_name" type="text" name="name" maxlength="100" required value="">
                <label for="id_end">End Date</label>
                <input id="id_end" type="date" name="end" value="">
                <label for="id_description">Description</label>
                <textarea id="id_description" name="description" cols="50"></textarea>
                <button class="cancel">Cancel</button>
                <button type="submit">Create</button>
            </form>
        </script>

        <!-- sprint script -->
        <script type="text/html" id="sprint-template">
            <% if (sprint !== null) { %>
                <% if (!sprint.invalid) { %>
                    <h2><%- sprint.get('name') %></h2>
                    <span class="due-date">Due <%- sprint.get('end') %></span>
                    <p class="description">
                        <%- sprint.get('description') %>
                    </p>
                    <div class="tasks">
                    </div>
                <% }else{ %>
                    <h1>Sprint <%- sprint.get('id') %> not found.</h1>
                <% } %>
            <% }else{ %>
                <h1 class="loading">Loading...</h1>
            <% } %>
        </script>

        <!-- status script -->
        <script type="text/html" id="status-template">
            <h4><%- title %></h4>
            <div class="list">
            </div>
            <% if (sprint === null) { %>
                <button class="add" type="submit">Add Task</button>
            <% } %>
        </script>

        <!-- new task script -->
        <script type="text/html">
            <form class="add-task" action="" method="post">
                <label for="id_name">Task Name</label>
                <input id="id_name" type="text" name="name" maxlength="100" required>
                <label for="id_description">Description</label>
                <textarea id="id_description" name="description"></textarea>
                <button class="create" type="submit">Create</button>
                <button class="cancel" type="submit">Cancel</button>
            </form>
        </script>

        <!-- task item script -->
        <script type="text/html" id="task-item-template">
            <%- task.get('name') %>
        </script>

        <!-- task detail script -->
        <script type="text/html" id="task-detail-template">
            <div data-field="name" class="name" contenteditable="true">
                <%- task.get('name') %>
            </div>
            <div data-field="description" class="description" contenteditable="true">
                <%- task.get('description') %>
            </div>
            <div class="with-label">
                <div class="label">
                    Due:
                </div>
                <div data-field="due" class="due date" contenteditable="true">
                    <%- task.get('due') || empty %>
                </div>
            </div>
            <div class="with-label">
                <div class="label">
                    Assigned To:
                </div>
                <div data-field="assigned" class="assigned" contenteditable="true">
                    <%- task.get('assigned') || empty %>
                </div>
            </div>
            <form class="" action="index.html" method="post">
                <button class="cancel" type="submit">Close</button>
                <button class="save" hidden type="submit">Save</button>
            </form>
        </script>


    </head>
    <body>
        <div id="content"></div>

        <script type="text/javascript" src="{% static 'board/vendor/jquery-3.1.1.js' %}">
        </script>
        <script type="text/javascript" src="{% static 'board/vendor/underscore.js' %}">
        </script>
        <script type="text/javascript" src="{% static 'board/vendor/backbone.js' %}">
        </script>

        <script id="config" type="text/json">
            {
                "models": {},
                "collections": {},
                "session": null,
                "views": {},
                "router": null,
                "apiRoot": "{% url 'api-root' %}",
                "apiLogin": "{% url 'api-token' %}"
            }
        </script>

        <script type="text/javascript" src="{% static 'board/js/app.js' %}">
        </script>
        <script type="text/javascript" src="{% static 'board/js/socket.js' %}">
        </script>
        <script type="text/javascript" src="{% static 'board/js/models.js' %}">
        </script>
        <script type="text/javascript" src="{% static 'board/js/views.js' %}">
        </script>
        <script type="text/javascript" src="{% static 'board/js/router.js' %}">
        </script>
    </body>
</html>